/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check. LLM provider status is added with the chat.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description The saved profile and today's position (surplus, savings rate, net worth).
         */
        get: operations["get_profile_profile_get"];
        /**
         * Put Profile
         * @description Create or replace the profile.
         */
        put: operations["put_profile_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Goals
         * @description All goals: the active one first, then previous ones, newest first.
         */
        get: operations["list_goals_goals_get"];
        put?: never;
        /**
         * Create Goal
         * @description Create a goal. It becomes the active goal; the previous one is kept, inactive.
         *     The target date must be this month or later, and at most 50 years ahead.
         */
        post: operations["create_goal_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assumption Sets */
        get: operations["list_assumption_sets_assumptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assumptions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Assumption Set
         * @description Create or replace the assumption set with this name (e.g. `base`).
         */
        put: operations["put_assumption_set_assumptions__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Project the saved plan from the start of this month, optionally with what-if overrides.
         *     Overrides are never saved.
         */
        post: operations["simulate_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Run several scenarios on the saved plan, side by side. The first scenario is the
         *     baseline that the differences are measured from (by default, the current plan).
         */
        post: operations["compare_scenarios_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Saved scenario definitions (the built-in ones are not listed).
         */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        /**
         * Save Scenario
         * @description Save a scenario definition. A scenario with the same name is replaced.
         */
        post: operations["save_scenario_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssumptionSetOut */
        AssumptionSetOut: {
            /** Name */
            name: string;
            assumptions: components["schemas"]["Rates"];
        };
        /** CompareOut */
        CompareOut: {
            /** Assumption Set */
            assumption_set: string;
            /**
             * Baseline
             * @description Name of the scenario the differences are measured from.
             */
            baseline: string;
            /** Scenarios */
            scenarios: components["schemas"]["ComparedScenarioOut"][];
        };
        /** CompareRequest */
        CompareRequest: {
            /**
             * Assumption Set
             * @default base
             */
            assumption_set: string;
            /**
             * Scenarios
             * @description Scenarios to run; the first is the baseline. Omit to run the built-in scenarios (current plan first), then the saved ones.
             */
            scenarios?: components["schemas"]["ScenarioIn"][] | null;
        };
        /** ComparedScenarioOut */
        ComparedScenarioOut: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Saved Id
             * @description Id of a saved scenario; null for built-in ones.
             */
            saved_id: number | null;
            result: components["schemas"]["ScenarioResultOut"];
            vs_baseline: components["schemas"]["DeltaOut"];
        };
        /**
         * DeltaOut
         * @description How a scenario differs from the baseline (the first scenario compared).
         */
        DeltaOut: {
            /**
             * Goal Months Earlier
             * @description Months earlier (positive) or later (negative) that the goal is reached. Null when either scenario doesn't reach it within 50 years.
             */
            goal_months_earlier: number | null;
            /**
             * Value At Target Difference
             * @description Cash + investments on the target date, minus the baseline's.
             */
            value_at_target_difference: number;
        };
        /** GoalIn */
        GoalIn: {
            /** Name */
            name: string;
            /** @default other */
            goal_type: components["schemas"]["GoalType"];
            /**
             * Target Amount
             * @description Amount of cash + investments to reach.
             */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Description */
            description?: string | null;
        };
        /** GoalOut */
        GoalOut: {
            /** Name */
            name: string;
            /** @default other */
            goal_type: components["schemas"]["GoalType"];
            /**
             * Target Amount
             * @description Amount of cash + investments to reach.
             */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * GoalType
         * @enum {string}
         */
        GoalType: "house" | "emergency_fund" | "retirement" | "education" | "vehicle" | "travel" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /**
         * OverridesIn
         * @description Changes relative to the saved plan. Omitted fields keep their saved value.
         */
        OverridesIn: {
            /**
             * Monthly Investment Contribution
             * @description New monthly contribution. Can't be combined with the delta.
             */
            monthly_investment_contribution?: number | null;
            /**
             * Monthly Investment Contribution Delta
             * @description Change to the saved monthly contribution, e.g. 200 or -100.
             */
            monthly_investment_contribution_delta?: number | null;
            /** Monthly Net Income */
            monthly_net_income?: number | null;
            /** Monthly Expenses */
            monthly_expenses?: number | null;
            /** Annual Return */
            annual_return?: number | null;
            /** Annual Salary Growth */
            annual_salary_growth?: number | null;
            /** Annual Expense Growth */
            annual_expense_growth?: number | null;
        };
        /** PositionOut */
        PositionOut: {
            /** Total Monthly Income */
            total_monthly_income: number;
            /** Monthly Expenses */
            monthly_expenses: number;
            /** Monthly Debt Payment */
            monthly_debt_payment: number;
            /** Monthly Surplus */
            monthly_surplus: number;
            /**
             * Savings Rate
             * @description Surplus / income; null when income is 0.
             */
            savings_rate: number | null;
            /**
             * Liquid Assets
             * @description Cash + investments.
             */
            liquid_assets: number;
            /** Net Worth */
            net_worth: number;
        };
        /**
         * Profile
         * @description Profile values as output. No input limits: a what-if may legitimately exceed them.
         */
        Profile: {
            /** Monthly Net Income */
            monthly_net_income: number;
            /** Monthly Expenses */
            monthly_expenses: number;
            /** Cash */
            cash: number;
            /** Investments */
            investments: number;
            /** Monthly Investment Contribution */
            monthly_investment_contribution: number;
            /** Other Monthly Income */
            other_monthly_income: number;
            /** Debt Balance */
            debt_balance: number;
            /** Monthly Debt Payment */
            monthly_debt_payment: number;
            /** Age */
            age: number | null;
        };
        /** ProfileIn */
        ProfileIn: {
            /**
             * Monthly Net Income
             * @description Take-home pay; grows with salary growth.
             */
            monthly_net_income: number;
            /**
             * Monthly Expenses
             * @description Living expenses, excluding debt payments.
             */
            monthly_expenses: number;
            /**
             * Cash
             * @default 0
             */
            cash: number;
            /**
             * Investments
             * @default 0
             */
            investments: number;
            /**
             * Monthly Investment Contribution
             * @default 0
             */
            monthly_investment_contribution: number;
            /**
             * Other Monthly Income
             * @description Income that does not grow.
             * @default 0
             */
            other_monthly_income: number;
            /**
             * Debt Balance
             * @default 0
             */
            debt_balance: number;
            /**
             * Monthly Debt Payment
             * @default 0
             */
            monthly_debt_payment: number;
            /** Age */
            age?: number | null;
        };
        /** ProfileOut */
        ProfileOut: {
            profile: components["schemas"]["Profile"];
            /** @description Today's figures, computed from the profile. */
            position: components["schemas"]["PositionOut"];
        };
        /** Rates */
        Rates: {
            /**
             * Annual Return
             * @description Annual rate as a decimal: 0.05 = 5%.
             * @default 0
             */
            annual_return: number;
            /**
             * Annual Salary Growth
             * @description Annual rate as a decimal: 0.05 = 5%.
             * @default 0
             */
            annual_salary_growth: number;
            /**
             * Annual Expense Growth
             * @description Annual rate as a decimal: 0.05 = 5%.
             * @default 0
             */
            annual_expense_growth: number;
            /**
             * Annual Inflation
             * @description Displayed only; not used in calculations.
             * @default 0
             */
            annual_inflation: number;
        };
        /** SavedScenarioOut */
        SavedScenarioOut: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default {} */
            overrides: components["schemas"]["OverridesIn"];
            /** Id */
            id: number;
        };
        /** ScenarioIn */
        ScenarioIn: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default {} */
            overrides: components["schemas"]["OverridesIn"];
        };
        /** ScenarioResultOut */
        ScenarioResultOut: {
            /** Scenario Name */
            scenario_name: string;
            /** @description Effective profile, after overrides. */
            profile: components["schemas"]["Profile"];
            /** @description Effective assumptions, after overrides. */
            assumptions: components["schemas"]["Rates"];
            /** Monthly Contribution */
            monthly_contribution: number;
            /**
             * Monthly Surplus
             * @description Surplus in the first projected month.
             */
            monthly_surplus: number;
            /** Target Amount */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Months To Target Date */
            months_to_target_date: number;
            /**
             * Projected Goal Date
             * @description Null when not reached within 50 years.
             */
            projected_goal_date: string | null;
            /** Months To Goal */
            months_to_goal: number | null;
            /** Projected Value At Target Date */
            projected_value_at_target_date: number;
            /** Reaches Goal */
            reaches_goal: boolean;
            /** Shortfall */
            shortfall: number;
            /**
             * Required Monthly Contribution
             * @description Monthly amount that reaches the target on the target date at the assumed return. Null when the target date has arrived and the goal isn't reached.
             */
            required_monthly_contribution: number | null;
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
            /**
             * Snapshots
             * @description Monthly series, from today (month 0).
             */
            snapshots: components["schemas"]["SnapshotOut"][];
        };
        /** SimulateRequest */
        SimulateRequest: {
            /**
             * Assumption Set
             * @default base
             */
            assumption_set: string;
            /** @default {} */
            overrides: components["schemas"]["OverridesIn"];
            /**
             * Name
             * @description Defaults to "Current plan", or "What-if" when overrides are set.
             */
            name?: string | null;
        };
        /**
         * SnapshotOut
         * @description Balances at the end of the month, and the flows during it.
         */
        SnapshotOut: {
            /** Month */
            month: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Income */
            income: number;
            /** Expenses */
            expenses: number;
            /** Debt Payment */
            debt_payment: number;
            /** Surplus */
            surplus: number;
            /** Contribution */
            contribution: number;
            /** Withdrawal */
            withdrawal: number;
            /** Cash */
            cash: number;
            /** Investments */
            investments: number;
            /** Debt */
            debt: number;
            /** Liquid Assets */
            liquid_assets: number;
            /** Net Worth */
            net_worth: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarningCode
         * @enum {string}
         */
        WarningCode: "contribution_reduced" | "investments_withdrawn" | "liquid_funds_exhausted" | "debt_paid_off";
        /** WarningOut */
        WarningOut: {
            code: components["schemas"]["WarningCode"];
            /**
             * Month
             * @description First month in which the condition occurs.
             */
            month: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    put_profile_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"][];
                };
            };
        };
    };
    create_goal_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assumption_sets_assumptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssumptionSetOut"][];
                };
            };
        };
    };
    put_assumption_set_assumptions__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rates"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssumptionSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_scenarios_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScenarioOut"][];
                };
            };
        };
    };
    save_scenario_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScenarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
