/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check: the database and the chat's language model.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Plan
         * @description Turn a description ("I take home 2,400 a month…") into a draft of the plan forms, with
         *     the next question. Nothing is saved and the description isn't stored: the person checks
         *     the forms and saves them. Send the returned draft back with the next message.
         */
        post: operations["draft_plan_plan_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan Status
         * @description What's saved so far. Projections need both your finances and an active goal.
         */
        get: operations["plan_status_plan_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description The saved profile and today's position (surplus, savings rate, net worth).
         */
        get: operations["get_profile_profile_get"];
        /**
         * Put Profile
         * @description Create or replace the profile.
         */
        put: operations["put_profile_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Goals
         * @description All goals: the active one first, then previous ones, newest first.
         */
        get: operations["list_goals_goals_get"];
        put?: never;
        /**
         * Create Goal
         * @description Create a goal. It becomes the active goal; the previous one is kept, inactive.
         *     The target date must be this month or later, and at most 50 years ahead.
         */
        post: operations["create_goal_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assumption Sets */
        get: operations["list_assumption_sets_assumptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assumptions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Assumption Set
         * @description Create or replace the assumption set with this name (e.g. `base`).
         */
        put: operations["put_assumption_set_assumptions__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Project the saved plan from the start of this month, optionally with what-if overrides.
         *     Overrides are never saved.
         */
        post: operations["simulate_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate/uncertainty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Uncertainty
         * @description Run the saved plan (optionally with what-if overrides) over many simulated futures,
         *     with yearly investment returns varying around the assumed return at the profile's
         *     investment risk. The same seed always gives the same result.
         */
        post: operations["simulate_uncertainty_simulate_uncertainty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Run several scenarios on the saved plan, side by side. The first scenario is the
         *     baseline that the differences are measured from (by default, the current plan).
         */
        post: operations["compare_scenarios_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/compare/uncertainty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Uncertainty
         * @description Simulate the scenarios of the comparison, all on the same futures, so differences come
         *     from the scenarios rather than from luck. The first scenario is the baseline.
         */
        post: operations["compare_uncertainty_scenarios_compare_uncertainty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Saved scenario definitions (the built-in ones are not listed).
         */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        /**
         * Save Scenario
         * @description Save a scenario definition. A scenario with the same name is replaced.
         */
        post: operations["save_scenario_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description One conversational turn. The message is turned into a structured request, the
         *     deterministic engine runs it, and the reply explains the result. Nothing is saved:
         *     what-ifs never change the plan. Pass `thread_id` back to continue the conversation.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Projection
         * @description 'What does this mean for me?' for the Projection page: when the goal is reached, how
         *     often on time in simulated futures, and what being on time in 9 of 10 would take. Worded
         *     by the model when one is available and its text passes the checks.
         */
        post: operations["explain_projection_explain_projection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssumptionSetOut */
        AssumptionSetOut: {
            /** Name */
            name: string;
            assumptions: components["schemas"]["Rates"];
        };
        /** BandPointOut */
        BandPointOut: {
            /** Month */
            month: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * Thread Id
             * @description Continue a conversation. Omit to start a new one.
             */
            thread_id?: string | null;
            /**
             * Assumption Set
             * @description Used unless the message names another set.
             * @default base
             */
            assumption_set: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Thread Id */
            thread_id: string;
            /**
             * Reply
             * @description Commentary. The figures to display are in `results`.
             */
            reply: string;
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "clarification" | "declined";
            /**
             * Intent
             * @description How the message was understood (structured).
             */
            intent: components["schemas"]["RunProjection"] | components["schemas"]["GoalDate"] | components["schemas"]["RequiredContribution"] | components["schemas"]["WhatIf"] | components["schemas"]["Likelihood"] | components["schemas"]["CompareScenarios"] | components["schemas"]["ExplainAssumptions"] | components["schemas"]["NeedsClarification"] | components["schemas"]["Unsupported"];
            /** Assumption Set */
            assumption_set: string | null;
            /** @description The rates behind `results`. */
            assumptions: components["schemas"]["Rates"] | null;
            /**
             * Results
             * @description The engine's results; the first is the current plan (the baseline).
             */
            results: components["schemas"]["ComparedScenarioOut"][];
            /** @description For likelihood questions: the same scenarios over simulated futures. */
            futures: components["schemas"]["FuturesComparisonOut"] | null;
            /** Provider */
            provider: string;
            /**
             * Parsed By
             * @description Who understood the message: a model name, or "rules".
             */
            parsed_by: string;
            /**
             * Worded By
             * @description Who wrote the reply: a model name, or "template".
             */
            worded_by: string;
        };
        /** CompareOut */
        CompareOut: {
            /** Assumption Set */
            assumption_set: string;
            /**
             * Baseline
             * @description Name of the scenario the differences are measured from.
             */
            baseline: string;
            /** Scenarios */
            scenarios: components["schemas"]["ComparedScenarioOut"][];
        };
        /** CompareRequest */
        CompareRequest: {
            /**
             * Assumption Set
             * @default base
             */
            assumption_set: string;
            /**
             * Scenarios
             * @description Scenarios to run; the first is the baseline. Omit to run the built-in scenarios (current plan first), then the saved ones.
             */
            scenarios?: components["schemas"]["ScenarioIn"][] | null;
        };
        /**
         * CompareScenarios
         * @description 'Compare my options', 'show the scenarios'.
         */
        CompareScenarios: {
            /**
             * Assumption Set
             * @description Only when the user names one; otherwise the default set is used.
             */
            assumption_set?: ("conservative" | "base" | "optimistic") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "compare_scenarios";
        };
        /** CompareUncertaintyRequest */
        CompareUncertaintyRequest: {
            /**
             * Assumption Set
             * @default base
             */
            assumption_set: string;
            /**
             * Scenarios
             * @description Scenarios to run; the first is the baseline. Omit to run the built-in scenarios (current plan first), then the saved ones.
             */
            scenarios?: components["schemas"]["ScenarioIn"][] | null;
            /**
             * Paths
             * @description Number of simulated futures.
             * @default 1000
             */
            paths: number;
            /**
             * Seed
             * @description Fixes the random returns: the same seed always gives the same futures.
             * @default 2026
             */
            seed: number;
        };
        /** ComparedFuturesOut */
        ComparedFuturesOut: {
            /**
             * Probability By Target Date
             * @description Share of futures with cash + investments at or above the target on the target date.
             */
            probability_by_target_date: number;
            /**
             * Probability Margin
             * @description Half-width of the 95% interval of that share: 1.96 * sqrt(p(1 - p) / n).
             */
            probability_margin: number;
            goal_dates: components["schemas"]["GoalDatesOut"];
            /**
             * Not Reached Share
             * @description Share of futures that don't reach the target within the horizon.
             */
            not_reached_share: number;
            /** @description Cash + investments on the target date: 10th, 50th and 90th percentile. */
            value_at_target_date: components["schemas"]["PercentilesOut"];
            /** @description How far below the target the futures that miss it are. Null when none do. */
            shortfall_when_missed: components["schemas"]["PercentilesOut"] | null;
            /**
             * Required Monthly Investment
             * @description What it would take: the monthly investment that reaches the target by the target date in half, 8 in 10 and 9 in 10 of the futures.
             */
            required_monthly_investment: components["schemas"]["RequiredInvestmentOut"][];
            /** Name */
            name: string;
            /**
             * Saved Id
             * @description Id of a saved scenario; null for built-in ones.
             */
            saved_id: number | null;
            /**
             * Probability Difference
             * @description Share reaching the goal on time, minus the baseline's (0.03 = 3 points).
             */
            probability_difference: number;
        };
        /** ComparedScenarioOut */
        ComparedScenarioOut: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Saved Id
             * @description Id of a saved scenario; null for built-in ones.
             */
            saved_id: number | null;
            result: components["schemas"]["ScenarioResultOut"];
            vs_baseline: components["schemas"]["DeltaOut"];
        };
        /**
         * DeltaOut
         * @description How a scenario differs from the baseline (the first scenario compared).
         */
        DeltaOut: {
            /**
             * Goal Months Earlier
             * @description Months earlier (positive) or later (negative) that the goal is reached. Null when either scenario doesn't reach it within 50 years.
             */
            goal_months_earlier: number | null;
            /**
             * Value At Target Difference
             * @description Cash + investments on the target date, minus the baseline's.
             */
            value_at_target_difference: number;
        };
        /** DraftOut */
        DraftOut: {
            draft: components["schemas"]["PlanDraft"];
            /**
             * Understood
             * @description What this message changed, in words.
             */
            understood: string[];
            /** Question */
            question: string;
            /**
             * Still Missing
             * @description Required fields not filled yet.
             */
            still_missing: string[];
            /**
             * Optional Missing
             * @description Optional fields not answered yet.
             */
            optional_missing: string[];
            /**
             * Complete
             * @description Every required field is filled.
             */
            complete: boolean;
            /**
             * Read By
             * @description Who read the message: "rules", or a model's name.
             */
            read_by: string;
        };
        /** DraftRequest */
        DraftRequest: {
            /**
             * Message
             * @description What the person wrote. Omit to get the next question only.
             */
            message?: string | null;
            /** @description The draft so far, as returned last time: the server keeps nothing. */
            draft?: components["schemas"]["PlanDraft"];
        };
        /**
         * ExplainAssumptions
         * @description 'What are you assuming?'
         */
        ExplainAssumptions: {
            /**
             * Assumption Set
             * @description Only when the user names one; otherwise the default set is used.
             */
            assumption_set?: ("conservative" | "base" | "optimistic") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "explain_assumptions";
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Assumption Set
             * @default base
             */
            assumption_set: string;
        };
        /** FuturesComparisonOut */
        FuturesComparisonOut: {
            /** Assumption Set */
            assumption_set: string;
            investment_risk: components["schemas"]["InvestmentRisk"];
            /** Volatility */
            volatility: number;
            /** Paths */
            paths: number;
            /** Seed */
            seed: number;
            /**
             * Baseline
             * @description Name of the scenario the differences are measured from.
             */
            baseline: string;
            /**
             * Scenarios
             * @description Every scenario runs on the same simulated futures (the same seed).
             */
            scenarios: components["schemas"]["ComparedFuturesOut"][];
        };
        /**
         * GoalDate
         * @description 'When will I reach my goal?'
         */
        GoalDate: {
            /**
             * Assumption Set
             * @description Only when the user names one; otherwise the default set is used.
             */
            assumption_set?: ("conservative" | "base" | "optimistic") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "goal_date";
        };
        /**
         * GoalDatesOut
         * @description Dates by which 10%, 50% and 90% of futures have first reached the target. Null when
         *     that share of futures doesn't reach it within the horizon.
         */
        GoalDatesOut: {
            /** P10 */
            p10: string | null;
            /** P50 */
            p50: string | null;
            /** P90 */
            p90: string | null;
        };
        /** GoalIn */
        GoalIn: {
            /** Name */
            name: string;
            /** @default other */
            goal_type: components["schemas"]["GoalType"];
            /**
             * Target Amount
             * @description Amount of cash + investments to reach.
             */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Description */
            description?: string | null;
        };
        /** GoalOut */
        GoalOut: {
            /** Name */
            name: string;
            /** @default other */
            goal_type: components["schemas"]["GoalType"];
            /**
             * Target Amount
             * @description Amount of cash + investments to reach.
             */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /** GoalProgressOut */
        GoalProgressOut: {
            /**
             * Current Amount
             * @description Cash + investments today.
             */
            current_amount: number;
            /**
             * Remaining
             * @description Still to go; 0 once the target is covered.
             */
            remaining: number;
            /**
             * Fraction
             * @description Share of the target already there, from 0 to 1.
             */
            fraction: number;
        };
        /**
         * GoalType
         * @enum {string}
         */
        GoalType: "house" | "emergency_fund" | "retirement" | "education" | "vehicle" | "travel" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            llm: components["schemas"]["LlmStatus"];
        };
        /**
         * InvestmentRisk
         * @description How widely the portfolio's yearly returns vary (docs/PHASE2_DESIGN.md, 2.3).
         * @enum {string}
         */
        InvestmentRisk: "low" | "medium" | "high";
        /**
         * Likelihood
         * @description 'How likely am I to reach my goal?', optionally for a what-if ('...if I invest €200
         *     more?'). Answered from simulated futures, never from the model.
         */
        Likelihood: {
            /**
             * Assumption Set
             * @description Only when the user names one; otherwise the default set is used.
             */
            assumption_set?: ("conservative" | "base" | "optimistic") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "likelihood";
            overrides?: components["schemas"]["OverridesIn"] | null;
        };
        /** LlmStatus */
        LlmStatus: {
            /**
             * Provider
             * @description "mock" (no model) or the model name, e.g. "phi3".
             */
            provider: string;
            /**
             * Available
             * @description Whether the model answers. The chat works either way: without a model, rules and templates handle every message.
             */
            available: boolean;
        };
        /**
         * NeedsClarification
         * @description Understood partly, but something is missing, e.g. an amount without what it applies to.
         */
        NeedsClarification: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "needs_clarification";
            /** Question */
            question: string;
        };
        /**
         * OverridesIn
         * @description Changes relative to the saved plan. Omitted fields keep their saved value.
         */
        OverridesIn: {
            /**
             * Monthly Investment Contribution
             * @description New monthly contribution. Can't be combined with the delta.
             */
            monthly_investment_contribution?: number | null;
            /**
             * Monthly Investment Contribution Delta
             * @description Change to the saved monthly contribution, e.g. 200 or -100.
             */
            monthly_investment_contribution_delta?: number | null;
            /** Monthly Net Income */
            monthly_net_income?: number | null;
            /**
             * Monthly Net Income Delta
             * @description Change to monthly take-home pay, e.g. 300 or -200.
             */
            monthly_net_income_delta?: number | null;
            /** Monthly Expenses */
            monthly_expenses?: number | null;
            /**
             * Monthly Expenses Delta
             * @description Change to monthly expenses, e.g. -200 to spend 200 less.
             */
            monthly_expenses_delta?: number | null;
            /** Annual Return */
            annual_return?: number | null;
            /** Annual Salary Growth */
            annual_salary_growth?: number | null;
            /** Annual Expense Growth */
            annual_expense_growth?: number | null;
            /**
             * First Year Return
             * @description Return of the first year only, e.g. -0.3 for a 30% market drop.
             */
            first_year_return?: number | null;
        };
        /** PercentilesOut */
        PercentilesOut: {
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
        };
        /**
         * PlanDraft
         * @description The forms' values so far. Sent back by the browser with each message (the API keeps
         *     nothing). None means "not known yet"; 0 means "said to be nothing".
         */
        PlanDraft: {
            /** Monthly Net Income */
            monthly_net_income?: number | null;
            /** Other Monthly Income */
            other_monthly_income?: number | null;
            /** Monthly Expenses */
            monthly_expenses?: number | null;
            /** Cash */
            cash?: number | null;
            /** Investments */
            investments?: number | null;
            /** Monthly Investment Contribution */
            monthly_investment_contribution?: number | null;
            /** Debt Balance */
            debt_balance?: number | null;
            /** Monthly Debt Payment */
            monthly_debt_payment?: number | null;
            /** Age */
            age?: number | null;
            /** Goal Name */
            goal_name?: string | null;
            goal_type?: components["schemas"]["GoalType"] | null;
            /** Goal Target Amount */
            goal_target_amount?: number | null;
            /** Goal Target Date */
            goal_target_date?: string | null;
            /**
             * Notes
             * @description How a value was worked out: "€900 + €700".
             * @default {}
             */
            notes: {
                [key: string]: string;
            };
            /**
             * Skipped
             * @default []
             */
            skipped: string[];
            /**
             * Asked
             * @description The field the last question was about.
             */
            asked?: string | null;
            /**
             * To Check
             * @description Fields read by a language model, to be checked before saving.
             * @default []
             */
            to_check: string[];
            /**
             * Pending Goal Amount
             * @description A goal amount worked out from a percentage, waiting for a yes.
             */
            pending_goal_amount?: number | null;
        };
        /** PlanStatusOut */
        PlanStatusOut: {
            /**
             * Has Profile
             * @description Your finances have been saved.
             */
            has_profile: boolean;
            /**
             * Has Goal
             * @description An active goal exists.
             */
            has_goal: boolean;
            /**
             * Ready
             * @description Projections, comparisons and the chat can run.
             */
            ready: boolean;
        };
        /** PositionOut */
        PositionOut: {
            /** Total Monthly Income */
            total_monthly_income: number;
            /** Monthly Expenses */
            monthly_expenses: number;
            /** Monthly Debt Payment */
            monthly_debt_payment: number;
            /** Monthly Surplus */
            monthly_surplus: number;
            /**
             * Savings Rate
             * @description Surplus / income; null when income is 0.
             */
            savings_rate: number | null;
            /**
             * Liquid Assets
             * @description Cash + investments.
             */
            liquid_assets: number;
            /** Net Worth */
            net_worth: number;
        };
        /**
         * Profile
         * @description Profile values as output. No input limits: a what-if may legitimately exceed them.
         */
        Profile: {
            /** Monthly Net Income */
            monthly_net_income: number;
            /** Monthly Expenses */
            monthly_expenses: number;
            /** Cash */
            cash: number;
            /** Investments */
            investments: number;
            /** Monthly Investment Contribution */
            monthly_investment_contribution: number;
            /** Other Monthly Income */
            other_monthly_income: number;
            /** Debt Balance */
            debt_balance: number;
            /** Monthly Debt Payment */
            monthly_debt_payment: number;
            /** Age */
            age: number | null;
            investment_risk: components["schemas"]["InvestmentRisk"];
        };
        /** ProfileIn */
        ProfileIn: {
            /**
             * Monthly Net Income
             * @description Take-home pay; grows with salary growth.
             */
            monthly_net_income: number;
            /**
             * Monthly Expenses
             * @description Living expenses, excluding debt payments.
             */
            monthly_expenses: number;
            /**
             * Cash
             * @default 0
             */
            cash: number;
            /**
             * Investments
             * @default 0
             */
            investments: number;
            /**
             * Monthly Investment Contribution
             * @default 0
             */
            monthly_investment_contribution: number;
            /**
             * Other Monthly Income
             * @description Income that does not grow.
             * @default 0
             */
            other_monthly_income: number;
            /**
             * Debt Balance
             * @default 0
             */
            debt_balance: number;
            /**
             * Monthly Debt Payment
             * @default 0
             */
            monthly_debt_payment: number;
            /** Age */
            age?: number | null;
            /**
             * @description How widely yearly investment returns vary: low 5%, medium 10%, high 15% volatility. Used only by the uncertainty simulation.
             * @default medium
             */
            investment_risk: components["schemas"]["InvestmentRisk"];
        };
        /** ProfileOut */
        ProfileOut: {
            profile: components["schemas"]["Profile"];
            /** @description Today's figures, computed from the profile. */
            position: components["schemas"]["PositionOut"];
        };
        /** Rates */
        Rates: {
            /**
             * Annual Return
             * @description Annual rate as a decimal: 0.05 = 5%.
             * @default 0
             */
            annual_return: number;
            /**
             * Annual Salary Growth
             * @description Annual rate as a decimal: 0.05 = 5%.
             * @default 0
             */
            annual_salary_growth: number;
            /**
             * Annual Expense Growth
             * @description Annual rate as a decimal: 0.05 = 5%.
             * @default 0
             */
            annual_expense_growth: number;
            /**
             * Annual Inflation
             * @description Displayed only; not used in calculations.
             * @default 0
             */
            annual_inflation: number;
        };
        /** ReachedByOut */
        ReachedByOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Share
             * @description Share of futures that have reached the target by then.
             */
            share: number;
        };
        /**
         * RequiredContribution
         * @description 'How much do I need to invest each month to get there on time?' With `share`: in that
         *     share of simulated futures ('...to be 90% sure?'), otherwise at the assumed return.
         */
        RequiredContribution: {
            /**
             * Assumption Set
             * @description Only when the user names one; otherwise the default set is used.
             */
            assumption_set?: ("conservative" | "base" | "optimistic") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "required_contribution";
            /**
             * Share
             * @description E.g. 0.9 for 9 in 10 futures.
             */
            share?: number | null;
        };
        /** RequiredInvestmentOut */
        RequiredInvestmentOut: {
            /**
             * Share
             * @description Share of futures, e.g. 0.8 for 8 in 10.
             */
            share: number;
            /**
             * Monthly Amount
             * @description Invested each month from next month, counted like the required contribution: today's cash and investments plus this amount, without the leftover surplus. Null when the target date has arrived and the goal isn't reached.
             */
            monthly_amount: number | null;
        };
        /**
         * RunProjection
         * @description 'Am I on track?', 'show my projection'.
         */
        RunProjection: {
            /**
             * Assumption Set
             * @description Only when the user names one; otherwise the default set is used.
             */
            assumption_set?: ("conservative" | "base" | "optimistic") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run_projection";
        };
        /** SavedScenarioOut */
        SavedScenarioOut: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default {} */
            overrides: components["schemas"]["OverridesIn"];
            /** Id */
            id: number;
        };
        /** ScenarioIn */
        ScenarioIn: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default {} */
            overrides: components["schemas"]["OverridesIn"];
        };
        /** ScenarioResultOut */
        ScenarioResultOut: {
            /** Scenario Name */
            scenario_name: string;
            /** @description Effective profile, after overrides. */
            profile: components["schemas"]["Profile"];
            /** @description Effective assumptions, after overrides. */
            assumptions: components["schemas"]["Rates"];
            /** Monthly Contribution */
            monthly_contribution: number;
            /**
             * Monthly Surplus
             * @description Surplus in the first projected month.
             */
            monthly_surplus: number;
            /** Target Amount */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Months To Target Date */
            months_to_target_date: number;
            /**
             * Projected Goal Date
             * @description Null when not reached within 50 years.
             */
            projected_goal_date: string | null;
            /** Months To Goal */
            months_to_goal: number | null;
            /** Projected Value At Target Date */
            projected_value_at_target_date: number;
            /** Reaches Goal */
            reaches_goal: boolean;
            /** Shortfall */
            shortfall: number;
            /**
             * Required Monthly Contribution
             * @description Monthly amount that reaches the target on the target date at the assumed return. Null when the target date has arrived and the goal isn't reached.
             */
            required_monthly_contribution: number | null;
            goal_progress: components["schemas"]["GoalProgressOut"];
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
            /**
             * Snapshots
             * @description Monthly series, from today (month 0).
             */
            snapshots: components["schemas"]["SnapshotOut"][];
        };
        /** SimulateRequest */
        SimulateRequest: {
            /**
             * Assumption Set
             * @default base
             */
            assumption_set: string;
            /** @default {} */
            overrides: components["schemas"]["OverridesIn"];
            /**
             * Name
             * @description Defaults to "Current plan", or "What-if" when overrides are set.
             */
            name?: string | null;
        };
        /**
         * SnapshotOut
         * @description Balances at the end of the month, and the flows during it.
         */
        SnapshotOut: {
            /** Month */
            month: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Income */
            income: number;
            /** Expenses */
            expenses: number;
            /** Debt Payment */
            debt_payment: number;
            /** Surplus */
            surplus: number;
            /** Contribution */
            contribution: number;
            /** Withdrawal */
            withdrawal: number;
            /** Cash */
            cash: number;
            /** Investments */
            investments: number;
            /** Debt */
            debt: number;
            /** Liquid Assets */
            liquid_assets: number;
            /** Net Worth */
            net_worth: number;
        };
        /** SummaryOut */
        SummaryOut: {
            /**
             * Summary
             * @description Three to five sentences about the page.
             */
            summary: string;
            /**
             * Facts
             * @description What the summary was written from, chosen by code from the engine's results.
             */
            facts: string[];
            /**
             * Worded By
             * @description The model that reworded the facts (checked), or "template" for the facts as they are.
             */
            worded_by: string;
        };
        /** UncertaintyOut */
        UncertaintyOut: {
            /**
             * Probability By Target Date
             * @description Share of futures with cash + investments at or above the target on the target date.
             */
            probability_by_target_date: number;
            /**
             * Probability Margin
             * @description Half-width of the 95% interval of that share: 1.96 * sqrt(p(1 - p) / n).
             */
            probability_margin: number;
            goal_dates: components["schemas"]["GoalDatesOut"];
            /**
             * Not Reached Share
             * @description Share of futures that don't reach the target within the horizon.
             */
            not_reached_share: number;
            /** @description Cash + investments on the target date: 10th, 50th and 90th percentile. */
            value_at_target_date: components["schemas"]["PercentilesOut"];
            /** @description How far below the target the futures that miss it are. Null when none do. */
            shortfall_when_missed: components["schemas"]["PercentilesOut"] | null;
            /**
             * Required Monthly Investment
             * @description What it would take: the monthly investment that reaches the target by the target date in half, 8 in 10 and 9 in 10 of the futures.
             */
            required_monthly_investment: components["schemas"]["RequiredInvestmentOut"][];
            /** Scenario Name */
            scenario_name: string;
            /** Assumption Set */
            assumption_set: string;
            /** @description Effective assumptions, after overrides. */
            assumptions: components["schemas"]["Rates"];
            investment_risk: components["schemas"]["InvestmentRisk"];
            /**
             * Volatility
             * @description Yearly volatility of returns for the risk level.
             */
            volatility: number;
            /** Paths */
            paths: number;
            /** Seed */
            seed: number;
            /**
             * Horizon Months
             * @description Target date plus 10 years, at most 50 years.
             */
            horizon_months: number;
            /** Target Amount */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Months To Target Date */
            months_to_target_date: number;
            /**
             * Reached By
             * @description Each 1 January within the horizon, and the target date.
             */
            reached_by: components["schemas"]["ReachedByOut"][];
            /**
             * Bands
             * @description Cash + investments percentiles for every month, from today (month 0).
             */
            bands: components["schemas"]["BandPointOut"][];
        };
        /** UncertaintyRequest */
        UncertaintyRequest: {
            /**
             * Assumption Set
             * @default base
             */
            assumption_set: string;
            /** @default {} */
            overrides: components["schemas"]["OverridesIn"];
            /**
             * Name
             * @description Defaults to "Current plan", or "What-if" when overrides are set.
             */
            name?: string | null;
            /**
             * Paths
             * @description Number of simulated futures.
             * @default 1000
             */
            paths: number;
            /**
             * Seed
             * @description Fixes the random returns: the same seed always gives the same futures.
             * @default 2026
             */
            seed: number;
        };
        /**
         * Unsupported
         * @description Advice requests and anything outside the simulator's scope.
         */
        Unsupported: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "unsupported";
            /**
             * Reason
             * @enum {string}
             */
            reason: "advice" | "out_of_scope" | "not_understood";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarningCode
         * @enum {string}
         */
        WarningCode: "contribution_reduced" | "investments_withdrawn" | "liquid_funds_exhausted" | "debt_paid_off";
        /** WarningOut */
        WarningOut: {
            code: components["schemas"]["WarningCode"];
            /**
             * Month
             * @description First month in which the condition occurs.
             */
            month: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Message */
            message: string;
        };
        /**
         * WhatIf
         * @description 'What if I invest €200 more per month?' The plan itself is never changed.
         */
        WhatIf: {
            /**
             * Assumption Set
             * @description Only when the user names one; otherwise the default set is used.
             */
            assumption_set?: ("conservative" | "base" | "optimistic") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "what_if";
            overrides: components["schemas"]["OverridesIn"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    draft_plan_plan_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_status_plan_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanStatusOut"];
                };
            };
        };
    };
    get_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    put_profile_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"][];
                };
            };
        };
    };
    create_goal_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assumption_sets_assumptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssumptionSetOut"][];
                };
            };
        };
    };
    put_assumption_set_assumptions__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rates"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssumptionSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_uncertainty_simulate_uncertainty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UncertaintyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UncertaintyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_scenarios_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_uncertainty_scenarios_compare_uncertainty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareUncertaintyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FuturesComparisonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScenarioOut"][];
                };
            };
        };
    };
    save_scenario_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedScenarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_projection_explain_projection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
