"""initial schema

Revision ID: 1339a891fc0b
Revises:
Create Date: 2026-09-28 21:06:13.782625

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1339a891fc0b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assumption_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("annual_return", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("annual_salary_growth", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("annual_expense_growth", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("annual_inflation", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "annual_expense_growth > -1 AND annual_expense_growth <= 1",
            name=op.f("ck_assumption_sets_annual_expense_growth_range"),
        ),
        sa.CheckConstraint(
            "annual_inflation > -1 AND annual_inflation <= 1",
            name=op.f("ck_assumption_sets_annual_inflation_range"),
        ),
        sa.CheckConstraint(
            "annual_return > -1 AND annual_return <= 1",
            name=op.f("ck_assumption_sets_annual_return_range"),
        ),
        sa.CheckConstraint(
            "annual_salary_growth > -1 AND annual_salary_growth <= 1",
            name=op.f("ck_assumption_sets_annual_salary_growth_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assumption_sets")),
        sa.UniqueConstraint("name", name=op.f("uq_assumption_sets_name")),
    )
    op.create_table(
        "financial_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("monthly_net_income", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("other_monthly_income", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("monthly_expenses", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("investments", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "monthly_investment_contribution", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("debt_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("monthly_debt_payment", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("age BETWEEN 0 AND 120", name=op.f("ck_financial_profiles_age_range")),
        sa.CheckConstraint("cash >= 0", name=op.f("ck_financial_profiles_cash_gte_0")),
        sa.CheckConstraint(
            "debt_balance >= 0", name=op.f("ck_financial_profiles_debt_balance_gte_0")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_financial_profiles_single_profile")),
        sa.CheckConstraint(
            "investments >= 0", name=op.f("ck_financial_profiles_investments_gte_0")
        ),
        sa.CheckConstraint(
            "monthly_debt_payment >= 0",
            name=op.f("ck_financial_profiles_monthly_debt_payment_gte_0"),
        ),
        sa.CheckConstraint(
            "monthly_expenses >= 0", name=op.f("ck_financial_profiles_monthly_expenses_gte_0")
        ),
        sa.CheckConstraint(
            "monthly_investment_contribution >= 0",
            name=op.f("ck_financial_profiles_monthly_investment_contribution_gte_0"),
        ),
        sa.CheckConstraint(
            "monthly_net_income >= 0", name=op.f("ck_financial_profiles_monthly_net_income_gte_0")
        ),
        sa.CheckConstraint(
            "other_monthly_income >= 0",
            name=op.f("ck_financial_profiles_other_monthly_income_gte_0"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_profiles")),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "goal_type",
            sa.Enum(
                "house",
                "emergency_fund",
                "retirement",
                "education",
                "vehicle",
                "travel",
                "other",
                name="goaltype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("target_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("target_amount > 0", name=op.f("ck_goals_target_amount_gt_0")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.create_index(
            "uq_goals_single_active",
            ["is_active"],
            unique=True,
            sqlite_where=sa.text("is_active = 1"),
            postgresql_where=sa.text("is_active"),
        )

    op.create_table(
        "scenarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("overrides", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
        sa.UniqueConstraint("name", name=op.f("uq_scenarios_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenarios")
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_goals_single_active",
            sqlite_where=sa.text("is_active = 1"),
            postgresql_where=sa.text("is_active"),
        )

    op.drop_table("goals")
    op.drop_table("financial_profiles")
    op.drop_table("assumption_sets")
    # ### end Alembic commands ###
